Repository operate-first/service-catalog, pull requests merged in 2022-12, with the labels that each got.

#193 feat(SRE-portal): Update UI to support cluster and token input
  app-config.local.yaml
  plugins/web-terminal/package.json
  plugins/web-terminal/schema.d.ts
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#195 feat: Switch from our rhacm plugin to now upstreamed ocm plugins from janus
  app-config.local.yaml
  app-config.prod.yaml
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/catalog/resource.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/catalog.ts
  packages/backend/src/plugins/ocm.ts
  plugins/rhacm-backend/.eslintrc.js
  plugins/rhacm-backend/README.md
  plugins/rhacm-backend/package.json
  plugins/rhacm-backend/schema.d.ts
  plugins/rhacm-backend/src/constants.ts
  plugins/rhacm-backend/src/helpers/config.test.ts
  plugins/rhacm-backend/src/helpers/config.ts
  plugins/rhacm-backend/src/helpers/kubernetes.test.ts
  plugins/rhacm-backend/src/helpers/kubernetes.ts
  plugins/rhacm-backend/src/helpers/parser.test.ts
  plugins/rhacm-backend/src/helpers/parser.ts
  plugins/rhacm-backend/src/helpers/test_data/kubeconfig.yaml
  plugins/rhacm-backend/src/index.ts
  plugins/rhacm-backend/src/providers/ManagedClusterProvider.ts
  plugins/rhacm-backend/src/providers/index.ts
  plugins/rhacm-backend/src/run.ts
  plugins/rhacm-backend/src/service/router.ts
  plugins/rhacm-backend/src/setupTests.ts
  plugins/rhacm-common/.eslintrc.js
  plugins/rhacm-common/README.md
  plugins/rhacm-common/package.json
  plugins/rhacm-common/src/index.ts
  plugins/rhacm-common/src/setupTests.ts
  plugins/rhacm/.eslintrc.js
  plugins/rhacm/README.md
  plugins/rhacm/dev/index.tsx
  plugins/rhacm/package.json
  plugins/rhacm/src/components/ClusterAllocatableResourcesCard/ClusterAllocatableResourcesCard.tsx
  plugins/rhacm/src/components/ClusterAllocatableResourcesCard/index.ts
  plugins/rhacm/src/components/ClusterAvailableResourcesCard/ClusterAvailableResourcesCard.tsx
  plugins/rhacm/src/components/ClusterAvailableResourcesCard/index.ts
  plugins/rhacm/src/components/ClusterContext/ClusterContext.tsx
  plugins/rhacm/src/components/ClusterContext/index.ts
  plugins/rhacm/src/components/ClusterInfoCard/ClusterInfoCard.tsx
  plugins/rhacm/src/components/ClusterInfoCard/index.ts
  plugins/rhacm/src/components/ClusterStatusCard/ClusterStatusCard.tsx
  plugins/rhacm/src/components/ClusterStatusCard/index.ts
  plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
  plugins/rhacm/src/components/ClusterStatusPage/index.ts
  plugins/rhacm/src/components/TableCardFromData/TableCardFromData.tsx
  plugins/rhacm/src/components/TableCardFromData/index.ts
  plugins/rhacm/src/helpers/apiClient.ts
  plugins/rhacm/src/index.ts
  plugins/rhacm/src/plugin.test.ts
  plugins/rhacm/src/plugin.ts
  plugins/rhacm/src/routes.ts
  plugins/rhacm/src/setupTests.ts
  yarn.lock
Labels: size/XXL, approved, lgtm

#198 feat: fix OCM and allow new API locations
  app-config.yaml
  packages/backend/package.json
  yarn.lock
Labels: approved, size/S, lgtm

#199 feat: tweaks for ADRs, tech docs and home page
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/catalog/component.tsx
  packages/app/src/components/catalog/domain.tsx
  packages/app/src/components/catalog/shared/utils.tsx
  packages/app/src/components/catalog/system.tsx
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/components/search/SearchPage.tsx
  packages/backend/package.json
  packages/backend/src/plugins/search.ts
  yarn.lock
Labels: approved, size/L, lgtm

#200 fix: Fix build with webterminal internal plugin
  plugins/web-terminal/schema.d.ts
Labels: size/XS, lgtm

#201 chore: Allow manual techdocs generator trigger
  .github/workflows/techdocs-generate-and-publish.yaml
Labels: size/M, lgtm

#202 docs: Fix entity for which we generate docs
  .github/workflows/techdocs.yaml
Labels: size/XS

#203 feat: Update favicon to arrows
  packages/app/public/android-chrome-192x192.png
  packages/app/public/android-chrome-512x512.png
  packages/app/public/apple-touch-icon.png
  packages/app/public/favicon-16x16.png
  packages/app/public/favicon-32x32.png
  packages/app/public/favicon.ico
  packages/app/public/mstile-150x150.png
  packages/app/public/safari-pinned-tab.svg
Labels: approved, size/M, lgtm
