Repository operate-first/service-catalog, pull requests merged in 2022-10, with the labels that each got.

#106 feat: Create cluster status backend plugin
  .s2iignore
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  manifests/components/rbac/role.yaml
  packages/backend/src/index.ts
  packages/backend/src/plugins/cluster-status.ts
  plugins/cluster-status-backend/.eslintrc.js
  plugins/cluster-status-backend/README.md
  plugins/cluster-status-backend/package.json
  plugins/cluster-status-backend/schema.d.ts
  plugins/cluster-status-backend/src/index.ts
  plugins/cluster-status-backend/src/run.ts
  plugins/cluster-status-backend/src/service/router.ts
  plugins/cluster-status-backend/src/setupTests.ts
  plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
  plugins/cluster-status-backend/src/statusCheck/kubernetesApi.ts
  plugins/cluster-status-backend/src/types/types.ts
  yarn.lock
Labels: approved, size/XL, lgtm

#104 docs: Add docs for k8s plugin configuration
  docs/k8s-plugin-configuration.md
  mkdocs.yaml
Labels: approved, size/M, lgtm

#116 feat: Add jerry to cluster configs
  app-config.prod.yaml
Labels: approved, size/XS, lgtm

#117 hotfix: Lock S2I base image
  .s2ibase
Labels: approved, size/XS, lgtm

#111 feat: Add clusterwide status page
  packages/app/src/App.tsx
  packages/app/src/clusterClient.ts
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
  plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
  yarn.lock
Labels: approved, size/L, lgtm

#118 chore: Setup code scanning
  .github/workflows/codeql-analysis.yml
Labels: approved, size/M, lgtm

#119 feat: Update catalog UI layouts
  packages/app/src/App.tsx
  packages/app/src/components/catalog/EntityPage.tsx
  packages/app/src/components/catalog/api.tsx
  packages/app/src/components/catalog/component.tsx
  packages/app/src/components/catalog/domain.tsx
  packages/app/src/components/catalog/entityPage.tsx
  packages/app/src/components/catalog/group.tsx
  packages/app/src/components/catalog/resource.tsx
  packages/app/src/components/catalog/shared/InfoCard.tsx
  packages/app/src/components/catalog/shared/LayoutWrapper.tsx
  packages/app/src/components/catalog/shared/OverviewWrapper.tsx
  packages/app/src/components/catalog/shared/StatusCard.tsx
  packages/app/src/components/catalog/shared/Warning.tsx
  packages/app/src/components/catalog/shared/utils.tsx
  packages/app/src/components/catalog/system.tsx
  packages/app/src/components/catalog/user.tsx
Labels: size/XXL, approved, lgtm

#120 fix: Internal plugin missing from dependencies
  packages/backend/package.json
  yarn.lock
Labels: approved, size/XS, lgtm

#121 fix: Handle a case where claim is undefined
  plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
Labels: approved, size/XS, lgtm

#122 feat: Add docs icon to nav bar
  packages/app/src/components/Root/Root.tsx
Labels: approved, size/XS, lgtm

#123 fix: Correctly check if cluster name exists in config
  plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts
Labels: approved, size/XS, lgtm

#125 fix: Small sidebar tweaks
  packages/app/src/components/Root/Root.tsx
Labels: approved, size/XS, lgtm

#126 fix: Add nowrap to InfoCard name column
  packages/app/src/components/catalog/shared/InfoCard.tsx
Labels: approved, size/XS, lgtm

#129 chore: Remove build section from .aicoe-ci.yaml
  .aicoe-ci.yaml
  packages/backend/build-image.sh
Labels: approved, size/XS, lgtm

#130 chore: Remove duplicate packages
  packages/backend/package.json
  plugins/cluster-status-backend/package.json
  yarn.lock
Labels: approved, size/L, lgtm

#132 fix: Add patch for service account name
  manifests/overlays/dev/kustomization.yaml
Labels: approved, size/XS, lgtm

#133 feat: Upgrade backstage to version 1.6.0
  .gitignore
  .s2iignore
  app-config.yaml
  backstage.json
  manifests/components/rbac/role.yaml
  package.json
  packages/app/cypress.json
  packages/app/package.json
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/search/SearchPage.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/kubernetes.ts
  packages/backend/src/plugins/permission.ts
  packages/backend/src/plugins/scaffolder.ts
  packages/backend/src/types.ts
  plugins/cluster-status-backend/package.json
  yarn.lock
Labels: size/XXL, approved, lgtm

#134 chore: Simplify cluster status page
  packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
Labels: approved, size/S, lgtm

#148 feat: Add entity logo to info card
  packages/app/src/components/catalog/shared/InfoCard.tsx
Labels: approved, size/M, lgtm

#149 feat: Setup postgres search
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  packages/backend/package.json
  packages/backend/src/plugins/search.ts
  yarn.lock
Labels: approved, size/M, lgtm

#154 feat: Enable metrics and healthz endpoints
  manifests/base/deployment.yaml
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/metrics.ts
  packages/backend/src/plugins/healthcheck.ts
  yarn.lock
Labels: approved, size/L, lgtm

#155 chore: Update owners
  OWNERS
Labels: approved, size/S, lgtm

#158 chore: Remove unused routes
  packages/app/src/App.tsx
Labels: approved, size/S, lgtm

#157 feat: Add cluster details to individual clusters
  packages/app/package.json
  packages/app/src/clusterClient.ts
  packages/app/src/components/catalog/resource.tsx
  packages/app/src/components/catalog/shared/ClusterStatus.tsx
  packages/app/src/components/clusterStatusPage/ClusterStatusPage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#160 feat: Rename RHACM backend plugin
  packages/app/package.json
  packages/app/src/clusterClient.ts
  packages/app/src/components/catalog/shared/ClusterStatus.tsx
  packages/backend/package.json
  packages/backend/src/plugins/cluster-status.ts
  plugins/rhacm-backend/.eslintrc.js
  plugins/rhacm-backend/README.md
  plugins/rhacm-backend/package.json
  plugins/rhacm-backend/schema.d.ts
  plugins/rhacm-backend/src/index.ts
  plugins/rhacm-backend/src/run.ts
  plugins/rhacm-backend/src/service/router.ts
  plugins/rhacm-backend/src/setupTests.ts
  plugins/rhacm-backend/src/statusCheck/StatusCheck.ts
  plugins/rhacm-backend/src/statusCheck/kubernetesApi.ts
  plugins/rhacm-backend/src/types/types.ts
  yarn.lock
Labels: approved, size/S, lgtm

#161 refactor: Move frontend for RHACM into a separate package
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/catalog/resource.tsx
  packages/app/src/components/catalog/shared/ClusterStatus.tsx
  packages/backend/src/index.ts
  packages/backend/src/plugins/rhacm.ts
  plugins/rhacm-backend/package.json
  plugins/rhacm-backend/src/index.ts
  plugins/rhacm-backend/src/service/router.ts
  plugins/rhacm-backend/src/statusCheck/StatusCheck.ts
  plugins/rhacm-common/.eslintrc.js
  plugins/rhacm-common/README.md
  plugins/rhacm-common/package.json
  plugins/rhacm-common/src/index.ts
  plugins/rhacm-common/src/setupTests.ts
  plugins/rhacm/.eslintrc.js
  plugins/rhacm/README.md
  plugins/rhacm/dev/index.tsx
  plugins/rhacm/package.json
  plugins/rhacm/src/components/ClusterAllocatableResourcesCard/ClusterAllocatableResourcesCard.tsx
  plugins/rhacm/src/components/ClusterAllocatableResourcesCard/index.ts
  plugins/rhacm/src/components/ClusterAvailableResourcesCard/ClusterAvailableResourcesCard.tsx
  plugins/rhacm/src/components/ClusterAvailableResourcesCard/index.ts
  plugins/rhacm/src/components/ClusterContext/ClusterContext.tsx
  plugins/rhacm/src/components/ClusterContext/index.ts
  plugins/rhacm/src/components/ClusterInfoCard/ClusterInfoCard.tsx
  plugins/rhacm/src/components/ClusterInfoCard/index.ts
  plugins/rhacm/src/components/ClusterStatusCard/ClusterStatusCard.tsx
  plugins/rhacm/src/components/ClusterStatusCard/index.ts
  plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
  plugins/rhacm/src/components/ClusterStatusPage/index.ts
  plugins/rhacm/src/components/TableCardFromData/TableCardFromData.tsx
  plugins/rhacm/src/components/TableCardFromData/index.ts
  plugins/rhacm/src/helpers/apiClient.ts
  plugins/rhacm/src/index.ts
  plugins/rhacm/src/plugin.test.ts
  plugins/rhacm/src/plugin.ts
  plugins/rhacm/src/routes.ts
  plugins/rhacm/src/setupTests.ts
  yarn.lock
Labels: approved, size/XL, lgtm

#163 refactor: RHACM backend plugin
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  plugins/rhacm-backend/package.json
  plugins/rhacm-backend/schema.d.ts
  plugins/rhacm-backend/src/constants.ts
  plugins/rhacm-backend/src/helpers/config.ts
  plugins/rhacm-backend/src/helpers/kubernetes.ts
  plugins/rhacm-backend/src/helpers/parser.ts
  plugins/rhacm-backend/src/service/router.ts
  plugins/rhacm-backend/src/statusCheck/StatusCheck.ts
Labels: approved, size/L, lgtm
