Repository operate-first/service-catalog, pull requests merged in 2022-06, with the labels that each got.

#4 feat: Add owners file
  OWNERS
Labels: approved, size/S, lgtm

#2 feat(prod): Prepare manifests for production deployment
  .dockerignore
  .sops.yaml
  README.md
  app-config.dev.yaml
  app-config.local.yaml
  manifests/backstage/base/secret.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/postgres.yaml
  manifests/base/route.yaml
  manifests/base/secret.yaml
  manifests/base/service.yaml
  manifests/components/postgres-db/kustomization.yaml
  manifests/components/postgres-db/operator-group.yaml
  manifests/components/postgres-db/sub.yaml
  manifests/overlays/dev/kustomization.yaml
  manifests/overlays/dev/route.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/secret-generator.yaml
  manifests/overlays/prod/secret.enc.yaml
  manifests/postgress/base/kustomization.yaml
  packages/backend/Dockerfile
Labels: approved, size/L, lgtm

#6 feat(docs): Improve documentation
  README.md
Labels: approved, size/M, lgtm

#7 feat(prod): Update configs for production
  app-config.prod.yaml
  app-config.yaml
Labels: approved, size/XS, lgtm

#9 fix(prod): Remove security context from deployment
  manifests/base/deployment.yaml
Labels: approved, size/XS, lgtm

#10 fix: Change host for route
  README.md
  app-config.prod.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/route.yaml
Labels: approved, size/S, lgtm

#8 feat(s2i): Convert dockerfile to s2i image
  .aicoe-ci.yaml
  .s2i/bin/assemble
  .s2i/bin/run
  .s2iignore
  README.md
  packages/backend/Dockerfile
  packages/backend/build-image.sh
Labels: approved, size/L, lgtm

#24 feat: Add home page with catalog overview
  examples/components/service1.yaml
  examples/components/service2.yaml
  examples/components/service3.yaml
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/home/HomePage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#21 chore(dev): Add NVM config
  .nvmrc
  .s2iignore
  README.md
Labels: approved, size/XS, lgtm
