Repository operate-first/service-catalog, pull requests merged in 2022-07, with the labels that each got.

#27 feat(badges): Install badges plugin
  app-config.dev.yaml
  app-config.prod.yaml
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/catalog/EntityPage.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/badges.ts
  yarn.lock
Labels: approved, size/L, lgtm

#29 feat: Change branding to Operate First
  packages/app/public/android-chrome-192x192.png
  packages/app/public/android-chrome-512x512.png
  packages/app/public/apple-touch-icon.png
  packages/app/public/browserconfig.xml
  packages/app/public/favicon-16x16.png
  packages/app/public/favicon-32x32.png
  packages/app/public/favicon.ico
  packages/app/public/index.html
  packages/app/public/landing-logo.svg
  packages/app/public/manifest.json
  packages/app/public/mstile-150x150.png
  packages/app/public/safari-pinned-tab.svg
  packages/app/public/top-logo.svg
  packages/app/src/components/Logo/Logo.tsx
  packages/app/src/components/Root/LogoFull.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/home/HomePage.tsx
Labels: size/L, lgtm

#31 fix: Simplify logo annotation
  examples/components/service1.yaml
  examples/components/service2.yaml
  examples/components/service3.yaml
  packages/app/src/components/home/HomePage.tsx
Labels: approved, size/XS, lgtm

#30 fix: Make all home page tiles same height
  packages/app/src/components/home/HomePage.tsx
Labels: approved, size/XS, lgtm

#32 feat: Add ArgoCD plugin to service catalog
  app-config.yaml
  manifests/base/deployment.yaml
  manifests/overlays/prod/secret.enc.yaml
  packages/app/package.json
  packages/app/src/components/catalog/EntityPage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#35 feat: Install github insights plugin
  README.md
  packages/app/package.json
  packages/app/src/components/catalog/EntityPage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#40 chore: Fix repo pointers
  README.md
  app-config.local.yaml
Labels: approved, size/XS, lgtm

#38 feat: Install security insights plugin
  README.md
  packages/app/package.json
  packages/app/src/components/catalog/EntityPage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#33 feat(grafana): Install and configure grafana plugin
  .env.example
  README.md
  app-config.yaml
  manifests/base/deployment.yaml
  manifests/overlays/dev/secret.yaml
  manifests/overlays/prod/secret.enc.yaml
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/catalog/EntityPage.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#45 fix: Override default CSP directive for images
  app-config.yaml
Labels: approved, size/XS, lgtm

#46 feat: Hide grafana plugin if not available
  packages/app/src/components/catalog/EntityPage.tsx
Labels: approved, size/S, lgtm

#49 feat: Increase CPU limits for postgres and catalog
  manifests/base/deployment.yaml
  manifests/base/postgres.yaml
Labels: approved, size/XS, lgtm

#50 feat(security-insights): Remove secrity insights from the main view
  packages/app/src/components/catalog/EntityPage.tsx
Labels: approved, size/XS, lgtm

#56 feat(k8s-plugin): Add service account for plugin
  manifests/base/kustomization.yaml
  manifests/base/serviceaccount.yaml
Labels: approved, size/XS, lgtm

#58 feat(techdocs): Setup awsS3 as storage solution for techdocs publishing
  app-config.prod.yaml
  app-config.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/obc.yaml
Labels: approved, size/M, lgtm

#61 fix: Remove streching from home icons
  packages/app/src/components/home/HomePage.tsx
Labels: approved, size/XS, lgtm

#66 chore: Rename permission policy
  packages/backend/src/plugins/permission.ts
Labels: approved, size/XS, lgtm

#65 feat: Allow everyone to refresh an entity
  packages/backend/src/plugins/permission.ts
Labels: approved, size/XS, lgtm

#57 feat(plugins): Install and configure kuberntes plugin for smaug cluster
  .env.example
  README.md
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  manifests/base/deployment.yaml
  manifests/components/rbac/kustomization.yaml
  manifests/components/rbac/role.yaml
  manifests/components/rbac/rolebinding.yaml
  manifests/overlays/dev/kustomization.yaml
  package.json
  packages/app/package.json
  packages/app/src/components/catalog/EntityPage.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/kubernetes.ts
  yarn.lock
Labels: approved, size/XL, lgtm

#64 feat(techdocs): Add github workflows for publisher and listener
  .github/actions/docs-dispatch/action.yaml
  .github/workflows/techdocs-generate-and-publish.yaml
  .github/workflows/techdocs.yaml
  .pre-commit-config.yaml
  app-config.prod.yaml
Labels: approved, size/L, lgtm
