Repository operate-first/service-catalog, pull requests merged in 2022-08, with the labels that each got.

#70 feat(db): Add backup schedule and retention policy
  manifests/base/postgres.yaml
Labels: approved, size/XS, lgtm

#76 feat: Add common labels to manifests
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
Labels: approved, size/XS, lgtm

#78 feat: Add necessary configuration for new entities
  app-config.yaml
  packages/app/src/components/catalog/EntityPage.tsx
Labels: approved, size/M, lgtm

#82 fix: Resource limits for deployment
  manifests/base/deployment.yaml
Labels: approved, size/S, lgtm

#83 fix: Reference the correct label in service manifest
  manifests/base/service.yaml
Labels: approved, size/XS, lgtm

#81 feat: Add issue templates for service catalog
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: approved, size/M, lgtm

#73 docs: Migrate from README to MkDocs documentation
  .github/workflows/techdocs-template.yaml
  .github/workflows/techdocs.yaml
  README.md
  docs/configuring-entities.md
  docs/contributing.md
  docs/img/badges.png
  docs/index.md
  mkdocs.yaml
Labels: approved, size/XL, lgtm

#92 chore: Move constants file to src folder
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/constants.ts
Labels: approved, size/XS, lgtm

#93 chore: Fix entity name for the new catalog layout
  .github/workflows/techdocs.yaml
Labels: approved, size/XS, lgtm

#94 feat: Add tags and logo to readme
  README.md
Labels: approved, size/M, lgtm

#95 fix: Reduce db backup retention, increase storage size
  manifests/base/postgres.yaml
Labels: approved, size/XS, lgtm
