Repository operate-first/service-catalog, pull requests merged in 2022-09, with the labels that each got.

#80 feat: Prepare CI to build images
  .github/actions/build-service-catalog/action.yaml
  .github/actions/set-expiration/action.yaml
  .github/actions/test/action.yaml
  .github/workflows/pr.yaml
  .github/workflows/push.yaml
  .s2ibase
Labels: approved, size/L, lgtm

#99 feat: Add configs for all clusters to prod
  app-config.prod.yaml
  manifests/base/deployment.yaml
Labels: approved, size/M, lgtm

#100 chore: Simplify local dev config a bit
  .env.example
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  app-config.yaml
  docs/contributing.md
Labels: approved, size/M, lgtm

#101 fix: Use .metadata.title on Home page when available
  packages/app/src/components/home/HomePage.tsx
Labels: approved, size/XS, lgtm

#105 fix: Allow delete of orphans
  packages/backend/package.json
  packages/backend/src/plugins/permission.ts
  yarn.lock
Labels: approved, size/M, lgtm

#107 fix: Use the correct value for retention-full
  manifests/base/postgres.yaml
Labels: approved, size/XS, lgtm

#109 chore: Improve dev overlay for k8s deployment
  docs/contributing.md
  manifests/base/deployment.yaml
  manifests/overlays/dev/secret.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/S, lgtm
