Repository operate-first/service-catalog, pull requests merged in 2022-11, with the labels that each got.

#165 fix: Find hub cluster in config
  plugins/rhacm-backend/src/helpers/config.ts
Labels: approved, size/S, lgtm

#164 feat: Create catalog provider for ACM
  packages/app/src/components/catalog/resource.tsx
  packages/backend/src/plugins/catalog.ts
  plugins/rhacm-backend/src/index.ts
  plugins/rhacm-backend/src/providers/ManagedClusterProvider.ts
  plugins/rhacm-backend/src/providers/index.ts
Labels: approved, size/L, lgtm

#156 feat: Add proper error handler for k8s api
  plugins/rhacm-backend/src/helpers/kubernetes.ts
  plugins/rhacm-backend/src/service/router.ts
Labels: approved, size/M, lgtm

#167 feat: Adapt cluster page for backend refractor
  plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
Labels: approved, size/S, lgtm

#168 refactor: Optimize catalog api fetch with filter
  packages/app/src/components/home/HomePage.tsx
  plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
Labels: approved, size/M, lgtm

#169 feat: Add support for mermaid diagrams in techdocs
  .github/workflows/techdocs-generate-and-publish.yaml
  mkdocs.yaml
Labels: approved, size/XS, lgtm

#166 feat: Create Kubernetes Pod status overview card
  packages/app/src/components/DeploymentStatusCard/DeploymentStatusCard.tsx
  packages/app/src/components/catalog/component.tsx
Labels: approved, size/L, lgtm

#172 fix: Change HTTP probe to exec
  manifests/base/deployment.yaml
Labels: approved, size/S, lgtm

#174 fix: Increase timeout for probes
  manifests/base/deployment.yaml
Labels: approved, size/S, lgtm

#173 chore: Migrate secrets to vault
  manifests/base/deployment.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/secret-generator.yaml
  manifests/overlays/prod/secret.enc.yaml
Labels: approved, size/M, lgtm

#175 chore: Remove secret from base deployment
  manifests/base/kustomization.yaml
  manifests/base/secret.yaml
Labels: approved, size/XS, lgtm

#184 fix: Raise proper error when hub cluster is undefined in the config
  plugins/rhacm-backend/src/helpers/config.ts
Labels: approved, size/XS, lgtm

#185 feat: Create LinkTiles component
  packages/app/src/components/LinkTiles/LinkTile.tsx
  packages/app/src/components/LinkTiles/LinkTiles.tsx
  packages/app/src/components/catalog/component.tsx
  packages/app/src/components/catalog/domain.tsx
  packages/app/src/components/catalog/resource.tsx
  packages/app/src/components/catalog/shared/OverviewWrapper.tsx
  packages/app/src/components/catalog/system.tsx
Labels: approved, size/L, lgtm

#188 chore: Remove unused function
  plugins/rhacm-backend/src/helpers/config.ts
Labels: approved, size/XS, lgtm

#187 chore: Update pre-commit to run prettier
  .pre-commit-config.yaml
  .prettierignore
  packages/app/public/index.html
  packages/app/src/App.tsx
  packages/app/src/components/DeploymentStatusCard/DeploymentStatusCard.tsx
  packages/app/src/components/LinkTiles/LinkTile.tsx
  packages/app/src/components/LinkTiles/LinkTiles.tsx
  packages/app/src/components/catalog/component.tsx
  packages/app/src/components/catalog/domain.tsx
  packages/app/src/components/catalog/entityPage.tsx
  packages/app/src/components/catalog/resource.tsx
  packages/app/src/components/catalog/shared/InfoCard.tsx
  packages/app/src/components/catalog/shared/StatusCard.tsx
  packages/app/src/components/catalog/system.tsx
  packages/app/src/components/home/HomePage.tsx
  packages/backend/src/index.ts
  packages/backend/src/plugins/auth.ts
  packages/backend/src/plugins/badges.ts
  packages/backend/src/plugins/healthcheck.ts
  packages/backend/src/plugins/rhacm.ts
  packages/backend/src/plugins/search.ts
  plugins/rhacm-backend/schema.d.ts
  plugins/rhacm-backend/src/helpers/config.ts
  plugins/rhacm-backend/src/helpers/kubernetes.ts
  plugins/rhacm-backend/src/helpers/parser.ts
  plugins/rhacm-backend/src/providers/ManagedClusterProvider.ts
  plugins/rhacm-backend/src/service/router.ts
  plugins/rhacm-common/src/index.ts
  plugins/rhacm/dev/index.tsx
  plugins/rhacm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
  plugins/rhacm/src/components/ClusterStatusPage/index.ts
  plugins/rhacm/src/components/TableCardFromData/TableCardFromData.tsx
  plugins/rhacm/src/components/TableCardFromData/index.ts
  plugins/rhacm/src/helpers/apiClient.ts
  plugins/rhacm/src/plugin.ts
Labels: approved, size/XL, lgtm

#190 feat:(SRE-portal) Initialize plugin
  packages/app/package.json
  plugins/web-terminal/.eslintrc.js
  plugins/web-terminal/README.md
  plugins/web-terminal/dev/index.tsx
  plugins/web-terminal/package.json
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
  plugins/web-terminal/src/components/TerminalComponent/index.ts
  plugins/web-terminal/src/components/TerminalComponent/static/xterm.css
  plugins/web-terminal/src/index.ts
  plugins/web-terminal/src/plugin.test.ts
  plugins/web-terminal/src/plugin.ts
  plugins/web-terminal/src/routes.ts
  plugins/web-terminal/src/setupTests.ts
  yarn.lock
Labels: approved, size/L, lgtm

#189 feat: Add prometheus alerts
  app-config.yaml
  packages/app/package.json
  packages/app/src/components/catalog/component.tsx
  yarn.lock
Labels: approved, size/L, lgtm

#191 fix: Add secret as a resource in dev manifests
  manifests/overlays/dev/kustomization.yaml
Labels: approved, size/XS, lgtm

#192 chore: Bump backstage to 1.8.2
  backstage.json
  package.json
  packages/app/package.json
  packages/app/public/index.html
  packages/app/src/components/Root/Root.tsx
  packages/backend/package.json
  plugins/rhacm-backend/package.json
  plugins/rhacm-common/package.json
  plugins/rhacm/package.json
  plugins/web-terminal/package.json
  yarn.lock
Labels: size/XXL, approved, lgtm

#170 docs: Add techdocs architecture explenation
  docs/configuring-entities.md
Labels: approved, size/M, lgtm

#186 test: Add tests for config.ts and parser.ts
  plugins/rhacm-backend/package.json
  plugins/rhacm-backend/src/helpers/config.test.ts
  plugins/rhacm-backend/src/helpers/config.ts
  plugins/rhacm-backend/src/helpers/kubernetes.test.ts
  plugins/rhacm-backend/src/helpers/parser.test.ts
  plugins/rhacm-backend/src/helpers/parser.ts
  plugins/rhacm-backend/src/helpers/test_data/kubeconfig.yaml
  plugins/rhacm-common/src/index.ts
  yarn.lock
Labels: approved, size/XL, lgtm
