Repository operate-first/service-catalog, pull requests merged in 2023-01, with the labels that each got.

#205 docs: Update documentation for ocm plugin
  docs/cluster-status-plugin.md
  docs/ocm-plugin.md
  mkdocs.yaml
Labels: approved, size/S, lgtm

#206 feat (SRE-portal): Client setup for webterminal
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
  plugins/web-terminal/src/components/TerminalComponent/utils/index.ts
  plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts
Labels: approved, size/L, lgtm

#208 chore: Upgrade ocm plugins to the latest version
  app-config.dev.yaml
  app-config.local.yaml
  app-config.prod.yaml
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, size/M, lgtm

#209 feat: Operate First theme
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/LinkTiles/LinkTile.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/catalog/shared/InfoCard.tsx
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/themes.tsx
  yarn.lock
Labels: approved, size/L, lgtm
