Repository operate-first/service-catalog, pull requests merged in 2023-02, with the labels that each got.

#211 feat: Upgrade Backstage to v1.10.1
  .github/workflows/codeql-analysis.yml
  backstage.json
  package.json
  packages/app/package.json
  packages/app/src/App.tsx
  packages/backend/package.json
  plugins/web-terminal/package.json
  yarn.lock
Labels: size/XXL, approved, lgtm

#210 feat: Use cluster annotation instead of form field
  plugins/web-terminal/package.json
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
Labels: approved, size/S, lgtm

#215 docs: Update readme to show the current backstage version
  .github/workflows/backstage-tag.yaml
  README.md
Labels: approved, size/M, lgtm

#214 feat: Enable changing of namespace in UI
  plugins/web-terminal/package.json
  plugins/web-terminal/schema.d.ts
  plugins/web-terminal/src/components/NamespacePickerDialog/NamespacePickerDialog.tsx
  plugins/web-terminal/src/components/NamespacePickerDialog/index.tsx
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
  plugins/web-terminal/src/components/TerminalComponent/utils/helpers.ts
  plugins/web-terminal/src/components/TerminalComponent/utils/index.ts
  plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts
  yarn.lock
Labels: approved, size/L, lgtm

#212 feat: Add simple README for the plugin
  plugins/web-terminal/README.md
Labels: approved, size/M, lgtm

#216 feat: Create runbooks component
  packages/app/package.json
  packages/app/src/components/catalog/shared/RunBooksCard.tsx
  yarn.lock
Labels: approved, size/M, lgtm

#218 feat: Add prometheus plugin annotations
  packages/app/package.json
  packages/backend/package.json
  packages/backend/src/plugins/catalog.ts
  yarn.lock
Labels: approved, size/M, lgtm

#219 fix: Fix originLocation.type check and prometheus.io/alert annotation
  packages/backend/src/plugins/catalog.ts
Labels: approved, size/XS, lgtm
